### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by RDFonseca82** [vuldb/vuldb-api-php-examples#1]
I create a new token and use with this script and receive this error

API RESPONSE HEADER FIELDS version: 3.62 format: json status: 401 lang: en error: API key unknown querylimitmax: 0 timestamp: 1712734993 rtt: 0 etag: a23e39943732148e-1a9ec40662da7b10-dcca48101505dd86 API REQUEST HEADER FIELDS timestamp: 1712734993 apikey: unknown userid: API RESULT DATA

**Comment by marcruef** [comment]
Thank you for your feedback. Can you please share your username and/or user id? Thanks.

**Comment by RDFonseca82** [comment]
i will register with google ricardo.fonseca@rdfonseca.com

**Comment by marcruef** [comment]
There is no user registered with this mail address. Therefore, you are not in possession of a valid API key yet anyway.

**Comment by RDFonseca82** [comment]
i'm logged in and i will create a token

![erro1](https://github.com/vuldb/vuldb-api-php-examples/assets/38105077/283c4758-8f9c-414d-9954-2c596bca35e3)
![erro2](https://github.com/vuldb/vuldb-api-php-examples/assets/38105077/0dde8c04-9b19-491f-b59a-17c4fdeb30b4)

**Comment by marcruef** [comment]
We don't know which platform are shown in your screenshots. This does not look like our service: https://vuldb.com ;)
